### ISSUE TITLE
[BUG]: Failure while installing any PUP firmware file: stl_vector.h:1130: Assertion '__n < this->size()' failed.

### ISSUE THREAD

**Issue by lever1209** [Vita3K/Vita3K#3508]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Vita3K v0.2.0 3731-f0c22ea2e

### Description of Issue

[08:16:05.209] |I| [install_pup]: Extracting "/home/u1/Downloads/PSVUPDAT.PUP" to "/mnt/shingles/u1/vita3k/PUP_DEC"
[08:16:05.209] |I| [extract_pup_files]: PUP Version: 0x2
[08:16:05.209] |I| [extract_pup_files]: Firmware Version: 0x3740000
[08:16:05.209] |I| [extract_pup_files]: Build Number: 571880
[08:16:05.209] |I| [extract_pup_files]: Number Of Files: 36
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/stl_vector.h:1130: reference std::vector<unsigned char>::operator[](size_type): Assertion '__n < this->size()' failed.

### Expected Behavior

It should not be failing an assertion like this and install the PUP firmware to the emulated system.

### Reproduction Steps

Build the most recent (at the time of writing) version of vita3k from the AUR and install an official firmware PUP from sony.

### Log File

[08:15:59.120] |I| [init_config]: backend-renderer: OpenGL
[08:15:59.120] |I| [init_config]: log-level: Trace
[08:15:59.194] |I| [main]: Vita3K v0.2.0 3731-f0c22ea2e
[08:15:59.194] |I| [main]: OS: Arch Linux
[08:15:59.194] |I| [main]: CPU: AMD Ryzen 7 3700X 8-Core Processor | 16 Threads | 3.717 GHz
[08:15:59.194] |I| [main]: Available ram memory: 48121 MiB
[08:15:59.195] |I| [init]: Base path: "/opt/vita3k/"
[08:15:59.195] |I| [init]: Static assets path: "/opt/vita3k/"
[08:15:59.195] |I| [init]: Shared path: "/home/u1/.local/share/Vita3K"
[08:15:59.195] |I| [init]: Log path: "/home/u1/.cache/Vita3K"
[08:15:59.195] |I| [init]: User config path: "/home/u1/.config/Vita3K"
[08:15:59.195] |I| [init]: User cache path: "/home/u1/.cache/Vita3K"
[08:15:59.195] |I| [init]: User pref path: "/mnt/shingles/u1/vita3k/"
[08:15:59.355] |I| [create]: GPU = NVIDIA GeForce RTX 3070/PCIe/SSE2
[08:15:59.355] |I| [create]: GL_VERSION = 4.6.0 NVIDIA 565.77
[08:15:59.355] |I| [create]: GL_SHADING_LANGUAGE_VERSION = 4.60 NVIDIA
[08:15:59.355] |I| [create]: Your GPU supports shader interlock, some games that use programmable blending will have better performance.
[08:15:59.359] |W| [init_font]: Could not find firmware font file at "/mnt/shingles/u1/vita3k/sa0/data/font/pvf/ltn0.pvf", install firmware fonts package to fix this.
[08:15:59.362] |I| [init_font]: Using default Vita3K font.
[08:15:59.362] |W| [init_font]: Could not find firmware font file at "/mnt/shingles/u1/vita3k/sa0/data/font/pvf/ltn0.pvf", install firmware fonts package to fix this.
[08:15:59.364] |I| [init_font]: Using default Vita3K font.
[08:15:59.364] |W| [init_font]: Could not find firmware font file at "/mnt/shingles/u1/vita3k/sa0/data/font/pvf/ltn0.pvf", install firmware fonts package to fix this.
[08:15:59.366] |I| [init_font]: Using default Vita3K font.
[08:16:00.052] |I| [init_font]: Maximum font scale set to x2, Font atlas size: 32768x2048
[08:16:00.145] |W| [init_app_background]: Background not found for application Settings [NPXS10015].
[08:16:00.145] |W| [decryptRegistryFile]: Error while opening file: "/mnt/shingles/u1/vita3k/os0/kd/registry.db0", install firmware for solve this!
[08:16:00.145] |I| [init_theme]: Default icon found for system App NPXS10003.
[08:16:00.145] |I| [init_theme]: Default icon found for system App NPXS10008.
[08:16:00.145] |I| [init_theme]: Default icon found for system App NPXS10015.
[08:16:00.145] |I| [init_theme]: Default icon found for system App NPXS10026.
[08:16:00.146] |W| [init_theme_start_background]: Default start background not found, install firmware for fix this.
[08:16:00.332] |I| [update_app_compat_db]: Applications compatibility database is up to date.
[08:16:05.198] |W| [install_pup]: Path already exists, deleting it and reinstalling
[08:16:05.209] |I| [install_pup]: Extracting "/home/u1/Downloads/PSVUPDAT.PUP" to "/mnt/shingles/u1/vita3k/PUP_DEC"
[08:16:05.209] |I| [extract_pup_files]: PUP Version: 0x2
[08:16:05.209] |I| [extract_pup_files]: Firmware Version: 0x3740000
[08:16:05.209] |I| [extract_pup_files]: Build Number: 571880
[08:16:05.209] |I| [extract_pup_files]: Number Of Files: 36

### System Configuration

CPU: AMD Ryzen 7 3700X 8-Core Processor | 16 Threads | 3.717 GHz
GPU/Driver: nvidia-open-dkms, nvidia-utils, lib32-nvidia-utils
RAM: 48121MiB
OS: Arch Linux x86_64

**Comment by lever1209** [comment]
Core dump ran from a debug version of vita3k, or at least, my attempt at a debug build, i dont use cmake

```diff
diff --git a/PKGBUILD b/PKGBUILD
index bc80fa1..ea6fda3 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -3,8 +3,8 @@
 # Contributor: aimileus < $(echo YWltaWxpdXNAcHJvdG9ubWFpbC5jb20K | base64 -d)
 
 _pkgname="vita3k"
-pkgname="$_pkgname-git"
-pkgver=r3546.ef89d019d
+pkgname="$_pkgname-git-debugbuild"
+pkgver=r3731.f0c22ea2e
 pkgrel=1
 pkgdesc="Experimental PlayStation Vita emulator"
 arch=('x86_64')
@@ -28,7 +28,7 @@ optdepends=(
        'vulkan-validation-layers: Descriptive vulkan errors'
 )
 provides=('vita3k')
-conflicts=('vita3k')
+conflicts=('vita3k' 'vita3k-git')
 source=(
        "$_pkgname"::"git+$url.git"
        "vita3k.desktop"
@@ -253,7 +253,7 @@ build() {
        # Configure
        cmake --preset ${BUILDPRESET} -DUSE_VITA3K_UPDATE=OFF -DXXH_X86DISPATCH_ALLOW_AVX=ON
        # Build
-       cmake --build build/${BUILDPRESET} --config Release
+       cmake --build build/${BUILDPRESET} --config Debug
 }
 
 package() {
@@ -266,7 +266,7 @@ package() {
 
        mkdir -p "$pkgdir/usr/bin/" "$pkgdir/opt/vita3k/"
 
-       cp -r "build/${BUILDPRESET}/bin/Release/"* "$pkgdir/opt/vita3k/"
+       cp -r "build/${BUILDPRESET}/bin/Debug/"* "$pkgdir/opt/vita3k/"
        ln -s "/opt/vita3k/Vita3K" "$pkgdir/usr/bin/vita3k"
 
        install -Dm644 "README.md" "$pkgdir/usr/share/doc/$_pkgname/README.md"
```

```yml
           PID: 551696 (vita3k)
           UID: 1000 (u1)
           GID: 1000 (u1)
        Signal: 6 (ABRT)
     Timestamp: Wed 2025-01-22 08:55:55 AST (3min 46s ago)
  Command Line: vita3k
    Executable: /opt/vita3k/Vita3K
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole-522367.scope/tab(522378).scope
          Unit: user@1000.service
     User Unit: app-org.kde.konsole-522367.scope
         Slice: user-1000.slice
     Owner UID: 1000 (u1)
       Boot ID: 991009d4b82140b38a5702dc3365025f
    Machine ID: fbf7d99bdead4b9db9c332ea636a4a90
      Hostname: borzil
       Storage: /var/lib/systemd/coredump/core.vita3k.1000.991009d4b82140b38a5702dc3365025f.551696.1737550555000000.zst (present)
  Size on Disk: 49.2M
       Message: Process 551696 (vita3k) of user 1000 dumped core.
                
                Stack trace of thread 551738:
                #0  0x00007c0f8cdb63f4 n/a (libc.so.6 + 0x963f4)
                #1  0x00007c0f8cd5d120 raise (libc.so.6 + 0x3d120)
                #2  0x00007c0f8cd444c3 abort (libc.so.6 + 0x244c3)
                #3  0x00005ac592b0b5f0 n/a (n/a + 0x0)
                #4  0x00005ac59360c6a7 n/a (n/a + 0x0)
                #5  0x00005ac5935fe44c n/a (n/a + 0x0)
                #6  0x00005ac592e59663 n/a (n/a + 0x0)
                #7  0x00005ac592ba9914 n/a (n/a + 0x0)
                #8  0x00007c0f8cdb439d n/a (libc.so.6 + 0x9439d)
                #9  0x00007c0f8ce3949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 551697:
                #0  0x00007c0f8ce2b63d __poll (libc.so.6 + 0x10b63d)
                #1  0x00005ac59377b6fe n/a (n/a + 0x0)
                #2  0x00005ac59377cc61 n/a (n/a + 0x0)
                #3  0x00007c0f8cdb439d n/a (libc.so.6 + 0x9439d)
                #4  0x00007c0f8ce3949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 551699:
                #0  0x00007c0f8ce01733 clock_nanosleep (libc.so.6 + 0xe1733)
                #1  0x00007c0f8ce0d827 __nanosleep (libc.so.6 + 0xed827)
                #2  0x00005ac59377e22d n/a (n/a + 0x0)
                #3  0x00005ac59377cc61 n/a (n/a + 0x0)
                #4  0x00007c0f8cdb439d n/a (libc.so.6 + 0x9439d)
                #5  0x00007c0f8ce3949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 551698:
                #0  0x00007c0f8ce01733 clock_nanosleep (libc.so.6 + 0xe1733)
                #1  0x00007c0f8ce0d827 __nanosleep (libc.so.6 + 0xed827)
                #2  0x00005ac59377d65a n/a (n/a + 0x0)
                #3  0x00005ac59377cc61 n/a (n/a + 0x0)
                #4  0x00007c0f8cdb439d n/a (libc.so.6 + 0x9439d)
                #5  0x00007c0f8ce3949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 551696:
                #0  0x00007c0f8ce01733 clock_nanosleep (libc.so.6 + 0xe1733)
                #1  0x00007c0f8ce0d827 __nanosleep (libc.so.6 + 0xed827)
                #2  0x00005ac592c08779 n/a (n/a + 0x0)
                #3  0x00007c0f8cd45e08 n/a (libc.so.6 + 0x25e08)
                #4  0x00007c0f8cd45ecc __libc_start_main (libc.so.6 + 0x25ecc)
                #5  0x00005ac5927a0165 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
```

It appears i cant upload the dump directly to github because its over the max file size limit of 100mb, so this will have to do for now, let me know if you need the full dump and i will find a way to host it for you
