### ISSUE TITLE
Why there is no Windows Build in the release page?

### ISSUE THREAD

**Issue by rayman3003** [Vita3K/Vita3K#627]
Why there is no **Windows** Build in the release page?

Its only linux & osx:

https://github.com/Vita3K/Vita3K/releases/

**Comment by Zangetsu38** [comment]
Is normal Windows build is available on appveyor

**Comment by rayman3003** [comment]
> 
> 
> Is normal Windows build is available on appveyor

OK, But why not on Github release page? (linked above).

Github is faster & better than appveyor.

**Comment by 1whatleytay** [comment]
I don't think github can build anything. The builds you see on the release page are from Travis CI.

If you're looking for the windows build, its here https://ci.appveyor.com/project/Vita3K/vita3k/branch/master/artifacts

I think you're right though, it is a bit odd that the windows build isn't there. Might as well have all the builds on the release page.

**Comment by rayman3003** [comment]
> 
> 
> I don't think github can build anything. The builds you see on the release page are from Travis CI.
> 
> If you're looking for the windows build, its here https://ci.appveyor.com/project/Vita3K/vita3k/branch/master/artifacts
> 
> I think you're right though, it is a bit odd that the windows build isn't there. Might as well have all the builds on the release page.

I'm not complaining. And always appreciate the hard works, developers doing for Vita3K.

But I think its better to have windows release beside 2 other platforms, in the same github page. Bcuz github is faster & also github has release watch subscription, But appveyor doesn't.

**Comment by cxong** [comment]
Someone needs to add a github deploy section to the appveyor YAML, like
```yaml
deploy:
  provider: GitHub
  description: ''
  auth_token:
    secure: <secret token>
  prerelease: false
  force_update: true 	#to be in piece with Travis CI
  on:
    appveyor_repo_tag: true
```
